/** Mock para selects; sustituir por API / código postal cuando exista backend. */

export const PROVINCIAS_ES = [
  'Álava',
  'Albacete',
  'Alicante',
  'Almería',
  'Asturias',
  'Ávila',
  'Badajoz',
  'Barcelona',
  'Burgos',
  'Cáceres',
  'Cádiz',
  'Cantabria',
  'Castellón',
  'Ciudad Real',
  'Córdoba',
  'Cuenca',
  'Girona',
  'Granada',
  'Guadalajara',
  'Guipúzcoa',
  'Huelva',
  'Huesca',
  'Illes Balears',
  'Jaén',
  'La Coruña',
  'La Rioja',
  'Las Palmas',
  'León',
  'Lleida',
  'Lugo',
  'Madrid',
  'Málaga',
  'Murcia',
  'Navarra',
  'Ourense',
  'Palencia',
  'Pontevedra',
  'Salamanca',
  'Santa Cruz de Tenerife',
  'Segovia',
  'Sevilla',
  'Soria',
  'Tarragona',
  'Teruel',
  'Toledo',
  'Valencia',
  'Valladolid',
  'Vizcaya',
  'Zamora',
  'Zaragoza',
] as const;

export const LOCALIDADES_BY_PROVINCIA: Record<string, string[]> = {
  Madrid: ['Madrid', 'Alcalá de Henares', 'Móstoles', 'Fuenlabrada'],
  Barcelona: ['Barcelona', 'Hospitalet de Llobregat', 'Badalona', 'Terrassa'],
  Valencia: ['Valencia', 'Gandía', 'Sagunto'],
  Zamora: ['Zamora', 'Benavente', 'Toro'],
  Sevilla: ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra'],
};
